spring.datasource.url=jdbc:postgresql://localhost:5432/ecomonitor_db
spring.datasource.username=postgres
spring.datasource.password=6&7jjbt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.openweathermap.key=YOUR_OPENWEATHER_API_KEY_HERE
api.location.lat=48.6208
api.location.lon=22.2879