# URL ???? ?????: ???? ? ?????? ????????, ?????? ??, ?????? ? ???? ???????? ????
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ecomonitor_shcc_user:V6jIGpFZeCMuZf7PKlaPgs6db6kKJ4kd@dpg-d8g4lft9j78s73cjgrlg-a.frankfurt-postgres.render.com/ecomonitor_shcc}
spring.datasource.username=${DB_USERNAME:ecomonitor-db}
spring.datasource.password=${DB_PASSWORD:V6jIGpFZeCMuZf7PKlaPgs6db6kKJ4kd}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# API ????: ???? ? ?????? ?????? ? ?????? ??, ?????? ? ??? ???????? ????
api.openweathermap.key=${OPENWEATHER_API_KEY:200d62f64a6c3a52fd5f7c73615134b9}

# ?????????? ????????? ???????? ?????????? (??? ?????? ?????????????)
api.location.lat=48.6208
api.location.lon=22.2879