spring.datasource.url=jdbc:postgresql://localhost:5432/ecomonitor_db
spring.datasource.username=postgres
spring.datasource.password=6&7jjbt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

api.openweathermap.key=200d62f64a6c3a52fd5f7c73615134b9
api.location.lat=48.6208
api.location.lon=22.2879