# Параметри підключення до бази даних
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomonitor.db
spring.datasource.username=postgres
spring.datasource.password=6&7jjbt

# Налаштування Hibernate для автоматичного створення таблиць
# 'update' дозволяє програмі самостійно створювати таблиці на основі твоїх Entity-класів
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Порт, на якому буде доступний твій веб-інтерфейс
server.port=8080

# Твій унікальний ключ від OpenWeatherMap
openweathermap.api.key=200d62f64a6c3a52fd5f7c73615134b9
openweathermap.city=Uzhhorod